INFERANALYZE = '/usr/local/Cellar/infer/0.12.1/lib/infer/infer/bin/infer-analyze' --results-dir '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/AlphaPatternDrawable.java.c454b5c1133a0833627a1f46f39b42a7
cl1: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/ApiClientAsyncTask.java.1860b8cdd6b4bc4dc44e89b56d8f2ece
cl2: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/AutoStart.java.c33c2d305a96a2f90106d2a5b12c9f97
cl3: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/BaseDataObject.java.94e505620bcac735ea7485b93ec9f8c4
cl4: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/BudgetEnvelopes.java.b7617aa99ee4d5fd6e2a07caa586561a
cl5: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/BudgetEnvelopesAsyncTask.java.76a12bad8eafa164459a030ab1382897
cl6: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/BudgetEnvelopesSyncService.java.19293f9327d80bf4ab5ec69f1bb97a44
cl7: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/BuildConfig.java.2584ed0f66346e9114388e9af149531a
cl8: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/BuildConfig.java.83b7d3960b2e07350b30317de200f5a8
cl9: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/BuildConfig.java.c5bb127472e8d5ad13d01ab4510c9467
cl10: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/ColorPanelView.java.e1ff300959315535df02dc17174f7f56
cl11: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/ColorPickerDialog.java.15d2ce5ea5d9afd497c434de1a5dfce5
cl12: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/ColorPickerPreference.java.c4975c83445880516d5921cdab399352
cl13: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl13.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/ColorPickerView.java.4e56a47954423b720a1f27afc21aac68
cl14: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl14.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/DatabaseDefinition.java.8786898bac090cc2c47f68a5cb410223
cl15: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl15.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/DatabaseRestoreAsyncTask.java.bc653ee07e5e88bec1ea40bc6ebdee32
cl16: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl16.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/DatabaseSyncAsyncTask.java.f4f5399275a6d9914edc5309697f2a0e
cl17: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl17.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/DBMain.java.273e56619f093fe7d0f35341cedeed9f
cl18: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl18.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/DistributionDialogFragment.java.3e216110034becd70876c64631cbd860
cl19: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl19.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/EnvelopeDataObject.java.9c8d4f5c7c2c163aad42f7e34ada7f83
cl20: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl20.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/EnvelopeListArrayAdapter.java.842cccea0d91f7367c1c129bcf1e60e7
cl21: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl21.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/EnvelopeListFragment.java.786d808bda7323c490e86534c7b39854
cl22: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl22.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/EnvelopeManagerDialogFragment.java.2c9f287be47d4bf7e77dd32d81844ddb
cl23: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl23.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/EnvelopeManagerListArrayAdapter.java.472d37430e5e89888096aa913a6e1c86
cl24: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl24.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/EnvelopeSettingsDialogFragment.java.d5cdd447b14c858c0f56945f1a78245d
cl25: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl25.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/ExpenseDataObject.java.5e61049b955763354f23e25098b50671
cl26: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl26.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/ExpensesListArrayAdapter.java.21a5f6b6c94d8961c07058e32be59dad
cl27: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl27.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/FilteredCursorAdapter.java.4d55958dd1cc34a9e9bea17f0e7ddf42
cl28: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl28.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/MainActivity.java.27974c4c56cd337d1b75a4f211d16d8f
cl29: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl29.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.09ce6bc043344d22ac6e1a33c5b7829d
cl30: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl30.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.16c0ada4f6d9095a259682d2adf3f4bd
cl31: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl31.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.1763d21a1293e085c00049c8eb8940d8
cl32: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl32.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.19d4ed27d555a71d138800b5bf3123c8
cl33: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl33.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.22814b15cc965a9ddc65efe7c4abddb7
cl34: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl34.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.248841cf90aae5b027777f650924eeac
cl35: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl35.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.30ea485de1aa8fc49575d1678fc275ed
cl36: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl36.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.47bb234a1f16a0b1b623ca72997f3e91
cl37: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl37.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.726f8c9c1aea067e2122ea8e07f843f3
cl38: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl38.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.c8a41b4e4db0dc0350f00faffe55430d
cl39: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl39.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/R.java.e6962b9a8680b40a5afefb121a3830af
cl40: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl40.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/RearrangeableListView.java.3abe6c148aab73f81bef9d3c51c7c3aa
cl41: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl41.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/SettingsActivity.java.c4322dddeec284eda7ee0a3ad6d45f91
cl42: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl42.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/SettingsDataObject.java.b3528fc0e563f7a24089c62792f2ff80
cl43: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl43.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/SettingsFragment.java.004436c907524c7311b6a826419f6443
cl44: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl44.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/SyncActivity.java.99967951f36b7618a2af75c148fa7da2
cl45: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl45.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/TooltipHoverListener.java.0e07620860f296fbd6652ac326558819
cl46: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl46.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/TransactionDataObject.java.719c45255c1ca5614c9f82bd258b885d
cl47: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl47.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/TransactionDialogFragment.java.19aab5503548553de27cca92a6e4f42a
cl48: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl48.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/TransactionListArrayAdapter.java.d6296394b251157975ed9aeb345d0524
cl49: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl49.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/TransactionsFragment.java.709dcf176552be824e770097bf4f9859
cl50: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl50.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/TransactionsMonth.java.54d1cb5c361142cbd8c3aa7688bbba4e
cl51: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl51.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/captured/TransactionsMonthsAdapter.java.ecd32af9b9640c1309db0ee67d4d62e6
cl52: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/BudgetEnvelopes-master/infer-out/multicore/xcl52.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
