INFERANALYZE = '/usr/local/Cellar/infer/0.12.1/lib/infer/infer/bin/infer-analyze' --results-dir '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/BuildConfig.java.32cc29dd0fb09e426d52aa842ff6c862
cl1: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/BuildConfig.java.fa95b6507d88f8710042b0d8f13146f5
cl2: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/MainActivity.java.99c9aad909e890912c3941693a444e64
cl3: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/MainActivityMvp.java.1316904cfa040a49b8961716cfbd05bd
cl4: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/MainPresenter.java.d09ca6ec4fcd8982ea1bfd9cd410d1df
cl5: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/OneRepMaxTemplate.java.29b36796d01a650bf6a8231a82e162cc
cl6: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/PercentRepMax.java.79628f11f24cbe9b47530993fb26c722
cl7: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/R.java.21f2d72126b640418e8c48ff9f86ed7d
cl8: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/R.java.78126ecbdb8c910e7386dd1a1e617ed3
cl9: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl10: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/R.java.c5435fc866a38242805f8457d219bc02
cl11: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/captured/RecyclerViewAdapter.java.b9fc5f25c169d59f3e7b0613b68a23ad
cl12: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/One-Rep-Max-Calculator-master/infer-out/multicore/xcl12.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
