INFERANALYZE = '/usr/local/Cellar/infer/0.12.1/lib/infer/infer/bin/infer-analyze' --results-dir '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/BuildConfig.java.068dbe43900173a87734aa5d5a2a40ba
cl1: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/BuildConfig.java.1d6c39a899fa21c26016614f1b8b6cb2
cl2: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/ExampleUnitTest.java.a9ba3273b1262872ec46d49eb8de15ce
cl3: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/MainActivity.java.06367c22f80fdff2f0a68aea1672be7a
cl4: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.02f5e2e585c74b3ef0695eeab45f2ef9
cl5: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.030c1e532b482606e77cd89aad2b1284
cl6: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.0491aee41b2e89ef45d0a9bcaae5b11f
cl7: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.09fad7cad32f7642fc08bbedb65436e2
cl8: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.21f2d72126b640418e8c48ff9f86ed7d
cl9: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.3dbd9e316cc42f5f4b4dc644f72f71e1
cl10: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.4a8b79952e3ca5106c0500f148402b3e
cl11: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.4dac68a4a12f16c5b1dd6227bbe85323
cl12: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.5a735abd631d050591f33cd3a7d9a4c2
cl13: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl13.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.70c1366e9a88c88d0e510a35dda180ca
cl14: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl14.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.968388eff77adeb85d4b80522b71edca
cl15: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl15.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl16: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl16.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.a31a3a505366943a92b00f4e06c3e870
cl17: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl17.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.a3a7414bcb671140be079a93f84256a3
cl18: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl18.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.a7690f663399cd5bbcff90bd57145338
cl19: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl19.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.a9974d014cbe163cd86ab3dc17465606
cl20: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl20.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.b52479ac4e5053e814143666631cf52d
cl21: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl21.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.bb16a13413e8e00a0eca7f8eee235063
cl22: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl22.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.ca892a4ee249768ea1ffdda1610c4582
cl23: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl23.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.d548f8f469d5e6544f58e2f730a403fe
cl24: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl24.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.fbbb47ac27ba1858f65baba6044b1e6b
cl25: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl25.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/captured/R.java.fe74767c8d8df9911c249d4e1ba17b3d
cl26: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/HelloWorld/infer-out/multicore/xcl26.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
