INFERANALYZE = '/usr/local/Cellar/infer/0.12.1/lib/infer/infer/bin/infer-analyze' --results-dir '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/App_info.java.48621317b020e77e461dc981d04fa04d
cl1: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/BuildConfig.java.802d50138a6b6c13e00e00f733ceb131
cl2: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/BuildConfig.java.a4904ef68d4ed1a58d40ea494f1ca874
cl3: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/cheats_content.java.cc4505a78b50926c2600db18c356eb4b
cl4: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/contact_us.java.cef794973ca16f5cb33f113bc7f711ce
cl5: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/credits.java.0ef7596d5bb1f561500debe22538917f
cl6: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/custom_adapterCheats.java.7f1644a4402bf4413a0f5139d862bbc1
cl7: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/ExampleUnitTest.java.d28736c95d1c8ce930bef37287cf92cf
cl8: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/frag1.java.087e17dc5ab8fcce93da95a55d1609d7
cl9: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/frag1_honest.java.37181229ddbef4573c11a35a35496385
cl10: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/frag2.java.ff259822d886e872a20547869a188c0d
cl11: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/frag2_honest.java.6e6803cdc380b00cbf8842741d92b090
cl12: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/Honest_customAdapter.java.e3d7c55477b199a70bf86c9096ecbe91
cl13: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl13.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/honest_method.java.6e2190e44010b7631db70dc869842ea0
cl14: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl14.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/intro_cheats.java.9ced7601b7f9c151486a7e731dbad254
cl15: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl15.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/intro_honest.java.f1797e194e3768677ac694eca35f35f0
cl16: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl16.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/listofcheats.java.820ac135a2789f01d961c753b012d40e
cl17: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl17.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/onest_content.java.812bda1709d7dbd407adbe98bddbb1be
cl18: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl18.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.02849f16e7a9fcbce5657ceab2528614
cl19: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl19.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.21f2d72126b640418e8c48ff9f86ed7d
cl20: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl20.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.3f449c4186bd2ff2c70aae7b364dba41
cl21: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl21.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.4d6b9cece30f1cb3978e3b3a891aa7b4
cl22: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl22.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.5432418f97e6aeb8d2fc10ff2a64962d
cl23: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl23.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.944dce3476c6d5a136b2ac89fcebc5bc
cl24: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl24.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl25: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl25.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.c53188a45727fbc39b93edb3f162762e
cl26: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl26.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.c94c2e5c9a88d638c61f3916e98e3398
cl27: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl27.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.cf51053e546982aee841b3b230307608
cl28: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl28.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.e81359d13ced8908235a70757a577518
cl29: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl29.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/R.java.ed2872b26942afa5a8f13a8f68c107c1
cl30: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl30.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/road_chooser.java.3605520ea787ba153c58bc0049f74e74
cl31: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl31.cluster'
	@touch $@

#/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/captured/start_screen.java.86c11c607a69aea89e1d053e59bb6e18
cl32: 
	$(INFERANALYZE) --cluster '/Users/chris/Downloads/app-evolution-toolkit/SP2/Android/CrossRoads-master/infer-out/multicore/xcl32.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
